language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install -e .
  - pip install -e .[pytest]
script:
  - python setup.py pytest --addopts "--cov pypianoroll"
after_success:
  - coveralls
notifications:
  email: false
