language: python
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install -e .[test]
script:
  - pytest --cov="pypianoroll/" tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
